# Generated by Django 5.0.1 on 2024-03-04 14:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='media/covers/default.jpg', null=True, upload_to=api.models.upload_path),
        ),
    ]
